variables:
    RANCHER_URL: "http://165.227.74.95:8080"
    RANCHER_ACCESS_KEY: "D2C8240F1328F0DB1D08"
    RANCHER_SECRET_KEY: "V1x3sHR28Q55Z9QXw2srqZ4cjtnvSJgrtkLUMHMM"

# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest
services:
  - docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"


deploy:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --stack burnsforce --service burnsforce-main
  environment:
    name: production
    url: http://burnsforce.com
  only:
    - master
